name: Build, Scan and Push Docker Images
permissions:
  contents: write

on:
  push:
    branches:
      - dev

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      backend1: ${{ steps.filter.outputs.backend1 }}
      backend2: ${{ steps.filter.outputs.backend2 }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get Previous Commit
        id: prev-commit
        run: echo "PREV_COMMIT=$(git rev-parse HEAD^1)" >> $GITHUB_ENV
      - name: Detect Changed Files
        id: filter
        uses: dorny/paths-filter@v3
        with:
          base: ${{ env.PREV_COMMIT }}
          filters: |
            backend1:
              - 'backend1/**'
            backend2:
              - 'backend2/**'
            frontend:
              - 'frontend/**'

  build-and-scan-backend1:
    needs: detect-changes
    if: needs.detect-changes.outputs.backend1 == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Sanitize branch name
        id: vars
        run: echo "BRANCH_NAME_SANITIZED=${GITHUB_REF_NAME//\//-}" >> $GITHUB_ENV

      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v5
        with:
          context: backend1
          file: backend1/Dockerfile
          push: true
          tags: |
            docker.io/${{ secrets.DOCKER_USERNAME }}/backend1-dev:${{ env.BRANCH_NAME_SANITIZED }}-${{ github.sha::7 }}
            docker.io/${{ secrets.DOCKER_USERNAME }}/backend1-dev:dev-latest
          cache-from: type=registry,ref=docker.io/${{ secrets.DOCKER_USERNAME }}/backend1-dev:buildcache
          cache-to: type=registry,ref=docker.io/${{ secrets.DOCKER_USERNAME }}/backend1-dev:buildcache,mode=max

      - name: Set up Trivy
        uses: aquasecurity/setup-trivy@v0.2.0
        with:
          version: v0.64.1

      - name: Download Trivy HTML template
        run: curl -o html.tpl https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/html.tpl

      - name: Run Trivy HTML Scan
        run: |
          trivy image --format template --template @html.tpl \
            -o backend1-trivy-report.html \
            docker.io/${{ secrets.DOCKER_USERNAME }}/backend1-dev:${{ env.BRANCH_NAME_SANITIZED }}-${{ github.sha::7 }}

      - name: Upload Trivy HTML report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: trivy-report-backend1
          path: backend1-trivy-report.html

  build-and-scan-backend2:
    needs: detect-changes
    if: needs.detect-changes.outputs.backend2 == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Sanitize branch name
        id: vars
        run: echo "BRANCH_NAME_SANITIZED=${GITHUB_REF_NAME//\//-}" >> $GITHUB_ENV

      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v5
        with:
          context: backend2
          file: backend2/Dockerfile
          push: true
          tags: |
            docker.io/${{ secrets.DOCKER_USERNAME }}/backend2-dev:${{ env.BRANCH_NAME_SANITIZED }}-${{ github.sha::7 }}
            docker.io/${{ secrets.DOCKER_USERNAME }}/backend2-dev:dev-latest
          cache-from: type=registry,ref=docker.io/${{ secrets.DOCKER_USERNAME }}/backend2-dev:buildcache
          cache-to: type=registry,ref=docker.io/${{ secrets.DOCKER_USERNAME }}/backend2-dev:buildcache,mode=max

      - name: Set up Trivy
        uses: aquasecurity/setup-trivy@v0.2.0
        with:
          version: v0.64.1

      - name: Download Trivy HTML template
        run: curl -o html.tpl https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/html.tpl

      - name: Run Trivy HTML Scan
        run: |
          trivy image --format template --template @html.tpl \
            -o backend2-trivy-report.html \
            docker.io/${{ secrets.DOCKER_USERNAME }}/backend2-dev:${{ env.BRANCH_NAME_SANITIZED }}-${{ github.sha::7 }}

      - name: Upload Trivy HTML report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: trivy-report-backend2
          path: backend2-trivy-report.html

  build-and-scan-frontend:
    needs: detect-changes
    if: needs.detect-changes.outputs.frontend == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Sanitize branch name
        id: vars
        run: echo "BRANCH_NAME_SANITIZED=${GITHUB_REF_NAME//\//-}" >> $GITHUB_ENV

      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v5
        with:
          context: frontend
          file: frontend/Dockerfile
          push: true
          tags: |
            docker.io/${{ secrets.DOCKER_USERNAME }}/frontend-dev:${{ env.BRANCH_NAME_SANITIZED }}-${{ github.sha::7 }}
            docker.io/${{ secrets.DOCKER_USERNAME }}/frontend-dev:dev-latest
          cache-from: type=registry,ref=docker.io/${{ secrets.DOCKER_USERNAME }}/frontend-dev:buildcache
          cache-to: type=registry,ref=docker.io/${{ secrets.DOCKER_USERNAME }}/frontend-dev:buildcache,mode=max

      - name: Set up Trivy
        uses: aquasecurity/setup-trivy@v0.2.0
        with:
          version: v0.64.1

      - name: Download Trivy HTML template
        run: curl -o html.tpl https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/html.tpl

      - name: Run Trivy HTML Scan
        run: |
          trivy image --format template --template @html.tpl \
            -o frontend-trivy-report.html \
            docker.io/${{ secrets.DOCKER_USERNAME }}/frontend-dev:${{ env.BRANCH_NAME_SANITIZED }}-${{ github.sha::7 }}

      - name: Upload Trivy HTML report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: trivy-report-frontend
          path: frontend-trivy-report.html
