name: "check_commit_lint"
on:
  push:
    branches:
      - "feature/**"

jobs:
  commitlint:
    runs-on: ubuntu-latest

    # runs-on: [self-hosted, backend]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install commitlint
        run: npm install -D @commitlint/cli @commitlint/config-conventional

      - name: add commitlint config
        run: |
          echo "module.exports = { extends: ['@commitlint/config-conventional'] };" > commitlint.config.js

      - name: validate current commit
        if: github.event_name == 'push'
        run: npx commitlint --last --verbose

  deploy:
    runs-on: [self-hosted, backend]

    steps:
      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/susil/prod
            touch 1.txt
