name: lint the code

permissions:
  contents: read
  pull-requests: read

on:
  pull_request:
    branches: ["dev"]

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      backend1: ${{ steps.filter.outputs.backend1 }}
      backend2: ${{ steps.filter.outputs.backend2 }}
      frontend: ${{ steps.filter.outputs.frontend }}

    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend1:
              - 'backend1/**'
            backend2:
              - 'backend2/**'
            frontend:
              - 'frontend/**'

  lint:
    needs: detect-changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - service: backend1
            changed: ${{ needs.detect-changes.outputs.backend1 }}
          - service: backend2
            changed: ${{ needs.detect-changes.outputs.backend2 }}
          - service: frontend
            changed: ${{ needs.detect-changes.outputs.frontend }}
      fail-fast: false

    steps:
      - name: Skip if no changes
        if: matrix.changed != 'true'
        run: echo "No changes in ${{ matrix.service }}. Skipping linting."

      - uses: actions/checkout@v4
        if: matrix.changed == 'true'

      - uses: actions/setup-node@v4
        if: matrix.changed == 'true'
        with:
          node-version: "lts/*"
          cache: "yarn"
          cache-dependency-path: ${{ matrix.service }}/yarn.lock

      - name: Install dependencies and run lint
        if: matrix.changed == 'true'
        working-directory: ${{ matrix.service }}
        run: |
          yarn install --frozen-lockfile
          yarn lint
