name: Lint the Code

permissions:
  contents: read
  pull-requests: read

on:
  pull_request:
    branches: ["dev"]

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      backend1: ${{ steps.filter.outputs.backend1 }}
      backend2: ${{ steps.filter.outputs.backend2 }}
      frontend: ${{ steps.filter.outputs.frontend }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: |
            backend1:
              - 'backend1/src/**'
            backend2:
              - 'backend2/src/**'
            frontend:
              - 'frontend/src/**'

  lint-backend1:
    needs: detect-changes
    if: needs.detect-changes.outputs.backend1 == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Ssetup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "yarn"
          cache-dependency-path: backend1/yarn.lock

      - name: install dependency
        working-directory: backend1
        run: yarn install --frozen-lockfile

      - name: lint backend1
        working-directory: backend1
        run: yarn lint

  lint-backend2:
    needs: detect-changes
    if: needs.detect-changes.outputs.backend2 == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "yarn"
          cache-dependency-path: backend2/yarn.lock

      - name: install dependency
        working-directory: backend2
        run: yarn install --frozen-lockfile

      - name: lint backend2
        working-directory: backend2
        run: yarn lint

  lint-frontend:
    needs: detect-changes
    if: needs.detect-changes.outputs.frontend == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "yarn"
          cache-dependency-path: frontend/yarn.lock

      - name: install dependency
        working-directory: frontend
        run: yarn install --frozen-lockfile

      - name: lint frontend
        working-directory: frontend
        run: yarn lint
